<LPHEADER>
<HTML>

<HEAD>
	<TITLE>Hits per Month per Url</TITLE>
	<LINK REL="StyleSheet" HREF="..\WebStats.css" TYPE="text/css"/>
</HEAD>

<BODY CLASS="StatsReport">

<TABLE BORDER="0" CELLSPACING="10" CELLPADDING="4" BGCOLOR="#D0D0D0">

<TR>
	<TH>%FIELDNAME_1%</TH>
	<TH>%FIELDNAME_2%</TH>
	<TH>%FIELDNAME_3%</TH>
</TR>

</LPHEADER>

<LPBODY>
<TR>
	<TD BGCOLOR="%FIELD_4%">%FIELD_1%</TD>
	<TD BGCOLOR="%FIELD_4%">%FIELD_2%</TD>
	<TD BGCOLOR="%FIELD_4%" ALIGN="right">%FIELD_3%</TD>
</TR>
</LPBODY>

<LPFOOTER>
</TABLE>
</BODY>
</HTML>
</LPFOOTER>